authors:
  vuellosoph:
    name: Catsten Vuellings
    description: musician, developer, systems architect, philosopher, author, founder
    avatar: https://avatars.githubusercontent.com/u/95686480
  chamberbot:
    name: Chamberbot
    description: \"AI\" assistant for music chamber
    avatar: https://static.thenounproject.com/png/2195399-200.png
