"""
Change TOC for Releases Hook for Music Chamber.

An MkDocs ``on_post_page`` hook that rewrites the Table of Contents for
weekly release-list posts so that ``<h1>`` headings are the top-level TOC
entries and ``<h2>`` headings are nested beneath their parent ``<h1>``.

By default MkDocs Material treats the first ``<h1>`` as the page title and
starts the sidebar TOC at ``<h2>``, which turns the release list into one
large flat list of albums.  This hook post-processes the final HTML to
produce a two-level TOC that lets readers jump between named sections (e.g.
"Releases! Releases! Releases!" and "Earlier this week") as well as to
individual album entries.

``page.toc`` already carries the full heading hierarchy built by MkDocs, so
there is no need to re-parse headings out of the rendered HTML.
"""

import logging

from bs4 import BeautifulSoup, Tag
from mkdocs.config import Config
from mkdocs.structure.pages import Page
from mkdocs.structure.toc import AnchorLink


log = logging.getLogger("mkdocs.plugins.change_toc_for_releases")


def _toc_item(soup: BeautifulSoup, anchor: AnchorLink) -> Tag:
    """Build a Material-theme TOC ``<li>`` element from an ``AnchorLink``.

    Called recursively for each level of nesting in ``page.toc``.

    ``anchor.title`` is an HTML string — entities such as ``&amp;`` are left
    encoded by MkDocs.  ``html.unescape`` decodes them to plain text so that
    BeautifulSoup re-encodes them correctly (and only once) in the output HTML.

    Args:
        soup: The parent ``BeautifulSoup`` document, used to create new tags.
        anchor: An ``AnchorLink`` from ``page.toc`` with ``.title``, ``.id``,
            and ``.children`` attributes.

    Returns:
        A ``<li class="md-nav__item">`` tag, with a nested ``<nav>`` / ``<ul>``
        block when the anchor has children.
    """
    # title = html_module.unescape(anchor.title)
    title = anchor.title

    li = soup.new_tag("li", attrs={"class": "md-nav__item"})
    a = soup.new_tag("a", href=f"#{anchor.id}", attrs={"class": "md-nav__link"})
    a.string = title
    li.append(a)

    if anchor.children:
        sub_nav = soup.new_tag("nav", attrs={"class": "md-nav", "aria-label": title})
        sub_ul = soup.new_tag("ul", attrs={"class": "md-nav__list"})
        for child in anchor.children:
            sub_ul.append(_toc_item(soup, child))
        sub_nav.append(sub_ul)
        li.append(sub_nav)

    return li

def on_post_page(output: str, page: Page, config: Config) -> str:
    """MkDocs hook: rebuild the TOC for release-list pages.

    Replaces the flat ``<h2>``-only Table of Contents generated by MkDocs
    Material with the full hierarchy from ``page.toc``, where ``<h1>``
    headings appear as top-level entries and deeper headings are nested
    beneath them.

    Only pages whose source path matches ``posts/**/releases.md`` are
    modified; all other pages are returned unchanged.

    Args:
        output: The fully-rendered HTML of the page.
        page: The MkDocs ``Page`` object.
        config: The global MkDocs configuration.

    Returns:
        The modified HTML string, or the original *output* if the page does
        not match or a required element cannot be found.
    """
    src = page.file.src_path

    if not (src.endswith("releases.md") and src.startswith("posts")):
        return output

    soup = BeautifulSoup(output, "html.parser")

    # Locate the Material-theme secondary navigation (right-side TOC).
    toc_nav = soup.find("nav", class_="md-nav--secondary")
    if not toc_nav:
        log.warning("change_toc_for_releases: TOC nav not found in %s", src)
        return output

    toc_label = soup.new_tag(
        "label", attrs={"class": "md-nav__title", "for": "__toc"}
    )
    toc_icon = soup.new_tag(
        "span", attrs={"class": "md-nav__icon md-icon"}
    )
    toc_label.append(toc_icon)
    toc_label.string = "Table of contents"

    new_toc_nav = soup.new_tag(
        "nav", attrs={"class": "md-nav md-nav--secondary", "aria-label": "Table of contents"}
    )

    new_list = soup.new_tag(
        "ul", attrs={"class": "md-nav__list", "data-md-scrollfix": ""}
    )
    for anchor in page.toc:
        new_list.append(_toc_item(soup, anchor))

    new_toc_nav.append(toc_label)
    new_toc_nav.append(new_list)

    toc_nav.replace_with(new_toc_nav)

    log.debug("change_toc_for_releases: rebuilt TOC for %s", src)

    return str(soup)
