"""
Hide Autogen Pages Hook for Music Chamber.

An MkDocs hook that removes auto-generated pages from the production build.
Pages are identified by the presence of ``Autogen`` in the ``categories``
list of their YAML front matter.

Behaviour
---------
* ``mkdocs serve``  — the file collection is returned unchanged so that
  autogenerated pages remain accessible for local preview.
* ``mkdocs build``  — every file whose front matter contains ``Autogen``
  in ``categories`` is excluded from the collection before any plugin or
  page-rendering step runs.

Build vs. serve detection
-------------------------
The ``on_startup`` event (MkDocs >= 1.4) receives a ``command`` argument
whose value is either ``"build"`` or ``"serve"``.  This hook stores that
value in the module-level ``_is_serve`` flag, which ``on_files`` then
consults.
"""

from __future__ import annotations

import logging
import re
from typing import Literal

import yaml
from mkdocs.config import Config
from mkdocs.structure.files import File, Files


# Matches a YAML front-matter block at the very start of a file.
# Handles both LF and CRLF line endings.
_FRONTMATTER_RE = re.compile(r"^---[ \t]*\r?\n(.*?)\r?\n---", re.DOTALL)

# Populated by on_startup(); consulted by on_files().
_is_serve: bool = False


# ---------------------------------------------------------------------------
# on_startup — detect build vs. serve
# ---------------------------------------------------------------------------

def on_startup(command: Literal["build", "serve"], dirty: bool) -> None:
    """Capture the MkDocs command so on_files can act accordingly.

    Args:
        command: Either ``"build"`` or ``"serve"``.
        dirty: Whether a dirty/incremental build was requested.
    """
    global _is_serve
    _is_serve = command == "serve"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _has_autogen_category(file: File) -> bool:
    """Return True if the file's front matter lists ``Autogen`` in categories.

    Only ``.md`` files are inspected; all other file types are passed through
    unchanged.  The function reads at most the first 4 096 bytes of the file
    so it stays fast even for very large posts.

    Args:
        file: A MkDocs File object.

    Returns:
        ``True`` when the file is a Markdown file whose YAML front matter
        contains ``"Autogen"`` in its ``categories`` list.
    """
    if not (file.src_path or "").endswith(".md"):
        return False

    abs_src = file.abs_src_path
    if not abs_src:
        return False

    try:
        with open(abs_src, encoding="utf-8") as fh:
            head = fh.read(4096)
    except (OSError, UnicodeDecodeError):
        return False

    match = _FRONTMATTER_RE.match(head)
    if not match:
        return False

    try:
        meta = yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return False

    if not isinstance(meta, dict):
        return False

    categories: list = meta.get("categories") or []
    return "Autogen" in categories


# ---------------------------------------------------------------------------
# on_files — filter the file collection
# ---------------------------------------------------------------------------

def on_files(files: Files, config: Config) -> Files:
    """Remove autogenerated files from the build file collection.

    Called by MkDocs after all files have been collected (including those
    produced by ``mkdocs-gen-files``).  When running ``mkdocs serve`` the
    collection is returned untouched so autogenerated pages remain
    accessible for local preview.

    Args:
        files: The full file collection assembled by MkDocs and all plugins.
        config: The global MkDocs configuration object.

    Returns:
        The original collection when serving locally, or a new Files
        instance with every ``Autogen``-tagged page removed when building.
    """
    if _is_serve:
        return files

    kept: list[File] = []
    removed: list[str] = []

    for f in files:
        if _has_autogen_category(f):
            removed.append(f.src_path)
        else:
            kept.append(f)

    return Files(kept)
